Fix errors when building without forced floating-point promotion flags
TEMPO uses forced floating-point promotion flags (e.g., `-fdefault-real-8` for GNU, `-r8`/`-real-size 64` for Intel)
in its `Makefile`s for compilation. This is fine as long as host models (e.g., UFS, MPAS, WRF) also use them.

However, when TEMPO is used within a host model that does not use those flags, the following build errors occur:

* GNU Fortran compiler

> test/unittests/test_tempo_utils_suite.F90:35:26:
>
>    35 |     call check(error, abs(calc_gamma_p(8.,8.) - value_from_wolfram) < 1.e-6_wp)
>       |                          1
> Error: Type mismatch in argument ‘a’ at (1); passed REAL(4) to REAL(8)
> test/unittests/test_tempo_utils_suite.F90:35:26:
>
>    35 |     call check(error, abs(calc_gamma_p(8.,8.) - value_from_wolfram) < 1.e-6_wp)
>       |                          1
> Error: Type mismatch in argument ‘x’ at (1); passed REAL(4) to REAL(8)

> src/module_mp_tempo_main.F90:392:15:
>
>   392 |           nc = tempo_cfgs%get_nc_val(val_land=nt_c_l, val_ocean=nt_c_o)
>       |               1
> Error: Type mismatch in argument ‘val_land’ at (1); passed REAL(8) to REAL(4)
> src/module_mp_tempo_main.F90:392:15:
>
>   392 |           nc = tempo_cfgs%get_nc_val(val_land=nt_c_l, val_ocean=nt_c_o)
>       |               1
> Error: Type mismatch in argument ‘val_ocean’ at (1); passed REAL(8) to REAL(4)

* Intel Fortran compiler

> test/unittests/test_tempo_utils_suite.F90(35): error #6633: The type of the actual argument differs from the type of the dummy argument.   [8.]
>     call check(error, abs(calc_gamma_p(8.,8.) - value_from_wolfram) < 1.e-6_wp)
> ---------------------------------------^
> test/unittests/test_tempo_utils_suite.F90(35): error #6633: The type of the actual argument differs from the type of the dummy argument.   [8.]
>     call check(error, abs(calc_gamma_p(8.,8.) - value_from_wolfram) < 1.e-6_wp)
> ------------------------------------------^
> compilation aborted for test/unittests/test_tempo_utils_suite.F90 (code 1)

> src/module_mp_tempo_main.F90(392): error #6633: The type of the actual argument differs from the type of the dummy argument.   [100.E6]
>           nc = tempo_cfgs%get_nc_val(val_land=nt_c_l, val_ocean=nt_c_o)
> ----------------------------------------------^
> src/module_mp_tempo_main.F90(392): error #6633: The type of the actual argument differs from the type of the dummy argument.   [50.E6]
>           nc = tempo_cfgs%get_nc_val(val_land=nt_c_l, val_ocean=nt_c_o)
> ----------------------------------------------------------------^
> compilation aborted for src/module_mp_tempo_main.F90 (code 1)

This commit fixes those build errors by explicitly specifying the correct `kind` parameter for `real` variables.